name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    runs-on: ubuntu-latest

    steps:
    - name: Debug Secrets
      run: |
        echo "SSH_HOSTNAME: ${{ secrets.SSH_HOSTNAME }}"
        echo "SSH_USER: ${{ secrets.SSH_USER }}"
        echo "WORK_DIR: ${{ secrets.WORK_DIR }}"
        echo "MAIN_BRANCH: ${{ secrets.MAIN_BRANCH }}"

    - name: Install SSH Keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOSTNAME }} >> ~/.ssh/known_hosts

    - name: Ensure Correct Permissions
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOSTNAME }} "
          sudo chown -R ${{ secrets.SSH_USER }}:${{ secrets.SSH_USER }} /var/www/ubc_ssc &&
          sudo chmod -R 755 /var/www/ubc_ssc"
        
    - name: Reset Repository and Pull Latest Changes
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOSTNAME }} "
          cd /var/www/ubc_ssc &&
          git fetch --all &&
          git reset --hard origin/${{ secrets.MAIN_BRANCH }} &&
          git clean -fdx &&
          exit"
        
    - name: Cleanup
      run: rm -rf ~/.ssh
